package com.example.selenium.javascriptexecution;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import com.example.selenium.misc.BaseTest;
import com.example.utils.LoggerUtil;

public class JavaScriptExecutionTest extends BaseTest {
    public JavascriptExecutor js;

    @BeforeMethod
    public void navigateTo() {
        driver.get(
                "https://gistcdn.githack.com/ravigajul/13fca01b060bf2a645c593e5c6cc16e4/raw/6a9fb9d69963cb8ecc575645e78abe370620b6b3/JavaScriptExecution.html");
        js = (JavascriptExecutor) driver;
    }

    @Test
    public void scrollToFullHeight() throws InterruptedException {
        Thread.sleep(3000);
        // Scroll to an element
        WebElement scrollableDiv = driver.findElement(By.id("scrollableDiv"));
        js.executeScript("arguments[0].scrollTop = arguments[0].scrollHeight;", scrollableDiv);
        LoggerUtil.info("Scrolled To full Height");
    }

    @Test
    public void clickHiddenElement() {
        // Click on a hidden element
        WebElement hiddenButton = driver.findElement(By.id("hiddenElement"));
        js.executeScript("arguments[0].click();", hiddenButton);
        LoggerUtil.info("Clicked hidden Element");
    }

    @Test
    public void setValueOfInputField() {
        // Set the value of an input field
        WebElement inputField = driver.findElement(By.id("inputField"));
        js.executeScript("arguments[0].value='JavaScript Executor Test';", inputField);
        LoggerUtil.info("Set input field value using javascript executor");
    }

    @Test
    public void generateAlert() throws InterruptedException {
        // Generate an alert
        js.executeScript("alert('This is an alert generated by JavaScript Executor');");
        Thread.sleep(2000);
        // Handle Alert
        Alert alert = driver.switchTo().alert();
        alert.accept();
        LoggerUtil.info("Accepted Java Script Alert");
    }

    @Test
    public void getPageTitle() {

        // Retrieve the page title and display it in a paragraph
        String title = (String) js.executeScript("return document.title;");
        js.executeScript("document.getElementById('pageTitle').innerText = 'Page Title: ' + arguments[0];", title);
        LoggerUtil.info("Retrieved page title using java script - " + title);
    }

    @Test
    public void scrollIntoView() throws InterruptedException {

        // Scroll to an element
        // WebElement scrollableDiv = driver.findElement(By.id("scrollableDiv"));
        // js.executeScript("arguments[0].scrollTop = arguments[0].scrollHeight;",
        // scrollableDiv);
        WebElement scrollTarget = driver.findElement(By.id("scrollTarget"));
        JavascriptExecutor js = (JavascriptExecutor) driver;
        js.executeScript("arguments[0].scrollIntoView(true);", scrollTarget);
        WebElement scrolledElement = wait.until(driver -> driver.findElement(By.id("visibleOnScroll")));
        assert scrolledElement.getText().equals("You have scrolled to me!");
        LoggerUtil.info("Scrolled into element's View");
    }

    @Test
    public void highlightElement() {
        WebElement textBox = driver.findElement(By.id("inputField"));
        WebElement alertButton = driver.findElement(By.id("alertButton"));
        JavascriptExecutor js = (JavascriptExecutor) driver;
        js.executeScript("arguments[0].style.border='5px solid red';arguments[1].style.border='5px solid green'",
                textBox, alertButton);
        LoggerUtil.info("Highlighted the element using javascript");

    }
}
