package com.example.selenium.javascriptexecution;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import com.example.selenium.BaseTest;

public class JavaScriptExecutionTest extends BaseTest {
    public JavascriptExecutor js;

    @BeforeMethod
    public void navigateTo() {
        driver.get(
                "https://gistcdn.githack.com/ravigajul/dee23b712aa43bc2625c0ca64475c7f8/raw/895c955497e174b9061d120e4e9b894ccad9f410/JavaScriptExecution.html");
        js = (JavascriptExecutor) driver;
    }

    @Test
    public void scrollToElement() throws InterruptedException {
        Thread.sleep(3000);
        // Scroll to an element
        WebElement scrollableDiv = driver.findElement(By.id("scrollableDiv"));
        js.executeScript("arguments[0].scrollTop = arguments[0].scrollHeight;", scrollableDiv);
    }

    @Test
    public void clickHiddenElement() {
        // Click on a hidden element
        WebElement hiddenButton = driver.findElement(By.id("hiddenElement"));
        js.executeScript("arguments[0].click();", hiddenButton);
    }

    @Test
    public void setValueOfInputField() {
        // Set the value of an input field
        WebElement inputField = driver.findElement(By.id("inputField"));
        js.executeScript("arguments[0].value='JavaScript Executor Test';", inputField);
    }

    @Test
    public void generateAlert() throws InterruptedException {
        // Generate an alert
        js.executeScript("alert('This is an alert generated by JavaScript Executor');");
        Thread.sleep(2000);
        // Handle Alert
        Alert alert = driver.switchTo().alert();
        alert.accept();
    }

    @Test
    public void getPageTitle() {

        // Retrieve the page title and display it in a paragraph
        String title = (String) js.executeScript("return document.title;");
        js.executeScript("document.getElementById('pageTitle').innerText = 'Page Title: ' + arguments[0];", title);

    }
}
